# Generated by Django 4.1.2 on 2022-11-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
