# Generated by Django 3.2.16 on 2022-11-14 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site_api', '0002_auto_20221114_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_site_api.blogpost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='comment',
            field=models.TextField(),
        ),
    ]
